postgres-addr: localhost:5433
spring:
  datasource:
    url: jdbc:postgresql://${postgres-addr}/testdb
    username: postgres
    password: postgres
outbox:
  relay:
    max-error-length: 500
    next-attempt-delay: 1s
